title: Sajjad Goudarzi
logo: /assets/img/sajjad_avatar2.png
description: Sajjad Goudarzi's CV
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  cv_url: /assets/cv/sajjadGoudarziCV2.pdf
  kaggle_url: https://www.kaggle.com/sajjad2goudarzi
  zip_url: /assets/cv/sajjadGoudarziCV.pdf